// =========================================================
// 📚 js/constants.js：アプリ全体で使う辞書データ・定数
// =========================================================
const genreMap = {
  Action: "アクション",
  Adventure: "アドベンチャー",
  Comedy: "コメディ",
  Drama: "ドラマ",
  Ecchi: "お色気",
  Fantasy: "ファンタジー",
  Horror: "ホラー",
  "Mahou Shoujo": "魔法少女",
  Mecha: "メカ",
  Music: "音楽",
  Mystery: "ミステリー",
  Psychological: "サイコ",
  Romance: "ロマンス",
  "Sci-Fi": "SF",
  "Slice of Life": "日常",
  Sports: "スポーツ",
  Supernatural: "超能力",
  Thriller: "スリラー",
};
window.translateGenres = function (genreStr) {
  if (!genreStr) return "";
  return genreStr
    .split(",")
    .map((g) => {
      let trimmed = g.trim();
      return genreMap[trimmed] ? genreMap[trimmed] : trimmed;
    })
    .join(", ");
};

const studioMap = {
  "8bit": "エイトビット",
  "A-1 Pictures": "A-1 Pictures",
  "A.C.G.T.": "A.C.G.T.",
  Actas: "アクタス",
  Ajiado: "亜細亜堂",
  "Arvo Animation": "アルボアニメーション",
  "Asahi Production": "旭プロダクション",
  "Bakken Record": "Bakken Record",
  "Bandai Namco Pictures": "バンダイナムコピクチャーズ",
  "Bibury Animation Studios": "バイブリーアニメーションスタジオ",
  "BN Pictures": "バンダイナムコピクチャーズ",
  Bones: "ボンズ",
  BONES: "ボンズ",
  "Brain's Base": "ブレインズ・ベース",
  "C-Station": "C-Station",
  C2C: "C2C",
  "Children's Playground Entertainment":
    "チルドレンズ・プレイグラウンド・エンタテインメント",
  "Cloud Hearts": "Cloud Hearts",
  CloverWorks: "CloverWorks",
  "CoMix Wave": "コミックス・ウェーブ・フィルム",
  "CoMix Wave Films": "コミックス・ウェーブ・フィルム",
  CONNECT: "CONNECT",
  CygamesPictures: "CygamesPictures",
  Daume: "童夢",
  "David Production": "デイヴィッドプロダクション",
  "David Productions": "デイヴィッドプロダクション",
  Diomedea: "ディオメディア",
  Diomedéa: "ディオメディア",
  diomedéa: "ディオメディア",
  "Doga Kobo": "動画工房",
  Drive: "ドライブ",
  "E&H Production": "E&H production",
  "EKACHI EPILKA": "エカチエピルカ",
  "EMT Squared": "EMTスクエアード",
  "Encourage Films": "エンカレッジフィルムズ",
  ENGI: "ENGI",
  "feel.": "feel.",
  "Felix Film": "FelixFilm",
  Gaina: "ガイナ",
  "Geek Toys": "ギークトイズ",
  "Geno Studio": "ジェノスタジオ",
  GoHands: "GoHands",
  Gonzo: "GONZO",
  Graphinica: "グラフィニカ",
  "HAL Film Maker": "ハルフィルムメーカー",
  "Hoods Entertainment": "フッズエンタテインメント",
  HORNETS: "HORNETS",
  "Hot Zipang": "HOTZIPANG",
  ILCA: "ILCA",
  "Imagica Infos": "IMAGICA Infos",
  "J.C. Staff": "J.C.STAFF",
  "J.C. STAFF": "J.C.STAFF",
  "J.C.STAFF": "J.C.STAFF",
  Jumondou: "寿門堂",
  "Kachidoki Studio": "勝鬨スタジオ",
  Khara: "カラー",
  "Kinema Citrus": "キネマシトラス",
  "Kyokuichi Tokyo Movie": "トムス・エンタテインメント",
  "Kyoto Animation": "京都アニメーション",
  "Lapin Track": "ラパントラック",
  "LARX ENTERTAINMENT": "ラークスエンタテインメント",
  "Lay-duce": "Lay-duce",
  Lerche: "Lerche",
  LIDENFILMS: "ライデンフィルム",
  "M.S.C": "M.S.C",
  Madhouse: "マッドハウス",
  MADHOUSE: "マッドハウス",
  "Magic Bus": "マジックバス",
  "Maho Film": "MAHO FILM",
  Makaria: "Makaria",
  Manglobe: "マングローブ",
  MAPPA: "MAPPA",
  "Marvy Jack": "マーヴィージャック",
  Millepensee: "ミルパンセ",
  "Mushi Production": "虫プロダクション",
  NAZ: "NAZ",
  "Nippon Animation": "日本アニメーション",
  Nomad: "ノーマッド",
  Nut: "NUT",
  NUT: "NUT",
  "Okuruto Noboru": "オクルトノボル",
  OLM: "OLM",
  Orange: "オレンジ",
  "P.A. Works": "P.A.WORKS",
  Passione: "パッショーネ",
  Peakys: "ピーキーズ",
  Pierrot: "ぴえろ",
  "Pierrot Plus": "ぴえろプラス",
  "Pine Jam": "PINE JAM",
  "Platinum Vision": "プラチナビジョン",
  "Polygon Pictures": "ポリゴン・ピクチュアズ",
  "Production I.G": "Production I.G",
  "Production I.G.": "Production I.G",
  "Project No.9": "project No.9",
  Quad: "QUAD",
  RADIX: "RADIX",
  Revoroot: "REVOROOT",
  Sanzigen: "サンジゲン",
  SANZIGEN: "サンジゲン",
  Satelight: "サテライト",
  "Science SARU": "サイエンスSARU",
  "Seven Arcs": "セブン・アークス",
  Shaft: "シャフト",
  SHAFT: "シャフト",
  "Shin-Ei Animation": "シンエイ動画",
  Shuka: "朱夏",
  "Silver Link": "SILVER LINK.",
  "Silver Link.": "SILVER LINK.",
  "SILVER LINK": "SILVER LINK.",
  "SILVER LINK.": "SILVER LINK.",
  "Staple Entertainment": "Staple Entertainment",
  "Studio 3Hz": "Studio 3Hz",
  "Studio Bind": "スタジオバインド",
  "Studio Blanc": "スタジオブラン",
  "Studio Chizu": "スタジオ地図",
  "Studio Colorido": "スタジオコロリド",
  "Studio Comet": "スタジオコメット",
  "Studio Deen": "スタジオディーン",
  "Studio DEEN": "スタジオディーン",
  "Studio Elle": "スタジオエル",
  "Studio Fantasia": "スタジオ・ファンタジア",
  "Studio Flad": "studio Flad",
  "Studio Gallop": "ぎゃろっぷ",
  "Studio Ghibli": "スタジオジブリ",
  "Studio Gokumi": "Studio五組",
  "Studio Hibari": "スタジオ雲雀",
  "Studio Kafka": "スタジオKafka",
  "Studio Kai": "スタジオKAI",
  "Studio Matrix": "スタジオマトリックス",
  "Studio Mother": "スタジオマザー",
  "Studio Pierrot": "ぴえろ",
  "Studio Puyukai": "スタジオぷYUKAI",
  "Studio Signpost": "スタジオ サインポスト",
  "Studio VOLN": "スタジオヴォルン",
  Sunrise: "サンライズ",
  "Sunrise Beyond": "サンライズビヨンド",
  SynergySP: "SynergySP",
  "Tatsunoko Production": "タツノコプロ",
  "Team TillDawn": "Team TillDawn",
  "Tear Studio": "ティアスタジオ",
  "Telecom Animation Film": "テレコム・アニメーションフィルム",
  "Tezuka Productions": "手塚プロダクション",
  TMS: "トムス・エンタテインメント",
  "TMS Entertainment": "トムス・エンタテインメント",
  TNK: "ティー・エヌ・ケー",
  "Toei Animation": "東映アニメーション",
  "Tokyo Movie": "トムス・エンタテインメント",
  "Tokyo Movie Shinsha": "トムス・エンタテインメント",
  Trigger: "トリガー",
  TRIGGER: "トリガー",
  TROYCA: "トロイカ",
  "Typhoon Graphics": "Typhoon Graphics",
  ufotable: "ufotable",
  "White Fox": "WHITE FOX",
  "WHITE FOX": "WHITE FOX",
  "Wit Studio": "WIT STUDIO",
  "WIT Studio": "WIT STUDIO",
  "WIT STUDIO": "WIT STUDIO",
  XEBEC: "XEBEC",
  "Yokohama Animation Lab": "横浜アニメーションラボ",
  "Yostar Pictures": "Yostar Pictures",
  "Zero-G": "ゼロジー",
  ZEXCS: "ゼクシズ",
  旭プロダクション: "旭プロダクション",
};
window.translateStudio = function (studioStr) {
  if (!studioStr) return "";
  let trimmed = studioStr.trim();
  return studioMap[trimmed] ? studioMap[trimmed] : trimmed;
};
